#!/bin/bash
set -e
ENV_FILE=".env"
ENV_FILE_TEMPLATE=".env.template"
DB="django_template"

if [ -z "$CI" ] && [ ! -f "$ENV_FILE" ]
then
    cp -v "$ENV_FILE_TEMPLATE" "$ENV_FILE"
    echo "Make sure to edit $ENV_FILE and run $0 again"
    exit 0
fi

if [ -z "$CI" ]
then
    dropdb "django_template" || echo "Database does not yet exist"
    createdb "django_template"
fi

./manage.py migrate
./manage.py seeddb
